name: Create a Draft Release

on:
    pull_request:
        types:
            - closed

jobs:
    release-if-merged:
        runs-on: ubuntu-latest
        if: |
          github.event.pull_request.merged == true &&
          startsWith(github.head_ref, 'release/v') &&
          endsWith(github.base_ref, 'live')
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Get the Release Name from the PR Branch Name and create a release
              run: |
                RELEASE_NAME-${HEAD_REFF//release\//}
                gh release create -d $RELEASE_NAME -t $RELEASE_NAME --target live
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                HEAD_REF: ${{ github.head_ref }}