name: Create a Pull Request for a Release branch

on:
    workflow_dispatch:
    push:
        branches:
            - release/*

jobs:
    create_pr:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout the repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            # Create a pull request (if one doesn't already exist)
            - name: Create Pull Request
              run: |
                pr_list=$(gh pr list --head "$GITHUB_HEAD_REF" --json number --jq '.[] | .number')
                if [ -n "$pr_list" ]; then    
                  echo "Pull request for branch $GITHUB_HEAD_REF already exists."    
                else    
                  gh pr create --fill --draft --base live    
                fi
              env:
                GITHUB_TOKEN: ${{ github.token }}